### ISSUE TITLE
Problem with upgrading requirements

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [Kyrluckechuck/tft-bot#7]
Hi,

i was planning to try out your fork but am running into problems with the < pip install -r requirements.txt >

it ran on the following problems so i first installed 
"Microsoft Visual Studio Community 2022 (64-Bit) - Current
Version 17.3.6"

but it seemed it is still the same problem

tx

------------------

`Building wheels for collected packages: opencv-python
  Building wheel for opencv-python (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\xxx\appdata\local\programs\python\python38\python.exe' 'c:\users\xxx\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\xxx\AppData\Local\Temp\tmpxgoy0cic'
       cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-5sz4vucv\opencv-python
  Complete output (332 lines):

  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 17 2022 x64 v143" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 17 2022 x64 v143" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 16 2019 x64 v142)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 16 2019 x64 v142)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 16 2019 x64 v142" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 16 2019

    could not find any instance of Visual Studio.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 16 2019 x64 v142" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 x64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Ninja

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 x64 v141)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 15 2017 x64 v141" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017

    could not find any instance of Visual Studio.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 15 2017 x64 v141" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 17 2022 x64 v143)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 17 2022 x64 v143)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 16 2019 x64 v142)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 16 2019 x64 v142)" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 x64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/xxx/AppData/Local/Temp/pip-install-5sz4vucv/opencv-python/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 x64 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.8 requires Microsoft Visual Studio 2022.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  Or with "Visual Studio 2019":

      https://visualstudio.microsoft.com/vs/

  Or with "Visual Studio 2022":

      https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for opencv-python
  Running setup.py clean for opencv-python
Failed to build opencv-python
ERROR: Could not build wheels for opencv-python which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 22.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by Kyrluckechuck** [comment]
Very interesting.

I see you're using Python 3.8, which while was recommended on the upstream fork may not be compatible with this -- I personally am using Python 3.10 installed via [Windows Store](https://www.microsoft.com/store/productId/9PJPW5LDXLZ5), could you try either installed Python 3.10 or the Windows Store variation and giving that a shot?

**Comment by RomeoAlphaEkko** [comment]
I'll give it a shot but most likely at the weekend

**Comment by Kyrluckechuck** [comment]
I've started tinkering with creating a pre-compiled executable, which would remove the need to install any specific Python version (or Python at all), as well as any requirements 

Please take a look at that, since that may be easier! 😅 
https://github.com/Kyrluckechuck/tft-bot/releases/tag/main-f448eb85

**Comment by RomeoAlphaEkko** [comment]
tried it on my windows tablet last week still ran on errors

so now as this event is over trying it on my main

got 1 error with permissions for pip on the requirements and reran permissions again without problems

but when starting by double clicking tft.py it directly closes - going over cmd gives:

C:\Users\xxx\Downloads\TFT-Bot-main>tft.py
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\TFT-Bot-main\tft.py", line 18, in <module>
    from click_helpers import click_right
  File "C:\Users\xxx\Downloads\TFT-Bot-main\click_helpers.py", line 12, in <module>
    from screen_helpers import find_image
  File "C:\Users\xxx\Downloads\TFT-Bot-main\screen_helpers.py", line 8, in <module>
    from system_helpers import resource_path
  File "C:\Users\xxx\Downloads\TFT-Bot-main\system_helpers.py", line 32, in <module>
    def bring_window_to_forefront(window_title: str, path_to_verify: str | None=None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by xChickens** [comment]
> tried it on my windows tablet last week still ran on errors
> 
> so now as this event is over trying it on my main
> 
> got 1 error with permissions for pip on the requirements and reran permissions again without problems
> 
> but when starting by double clicking tft.py it directly closes - going over cmd gives:
> 
> C:\Users\xxx\Downloads\TFT-Bot-main>tft.py Traceback (most recent call last): File "C:\Users\xxx\Downloads\TFT-Bot-main\tft.py", line 18, in from click_helpers import click_right File "C:\Users\xxx\Downloads\TFT-Bot-main\click_helpers.py", line 12, in from screen_helpers import find_image File "C:\Users\xxx\Downloads\TFT-Bot-main\screen_helpers.py", line 8, in from system_helpers import resource_path File "C:\Users\xxx\Downloads\TFT-Bot-main\system_helpers.py", line 32, in def bring_window_to_forefront(window_title: str, path_to_verify: str | None=None) -> None: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

This for sure is a Python version issue. This happens on Python 3.8, and you need Python 3.10.

**Comment by RomeoAlphaEkko** [comment]
> This for sure is a Python version issue. This happens on Python 3.8, and you need Python 3.10.

tx @xChickens just updated it, now starts and gives an error  "failed to set up logger, continue with caution!"

and does not start the game, moes goes not to find match but to the right out of the monitor, will try again later in the afternoon
